# Generated by Django 3.0.5 on 2020-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='userName',
        ),
    ]
