# Generated by Django 3.0.5 on 2020-04-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_auto_20200410_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='groupchat.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(related_name='group', to='groupchat.Message'),
        ),
    ]
