# Generated by Django 3.0.5 on 2020-04-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_auto_20200411_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fellowshipMember',
        ),
    ]
