# Generated by Django 3.0.5 on 2020-04-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_auto_20200410_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('publicKey', models.CharField(max_length=1024)),
                ('privateKey', models.CharField(max_length=1024)),
                ('symKey', models.CharField(max_length=1024)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupchat.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
