# Generated by Django 3.0.5 on 2020-04-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_auto_20200411_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', to='groupchat.User'),
        ),
    ]
