# Generated by Django 3.0.5 on 2020-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_auto_20200411_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='publicKey',
            field=models.CharField(max_length=64),
        ),
    ]
