# Generated by Django 3.0.5 on 2020-04-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0009_auto_20200412_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='GroupUser',
        ),
    ]
