# Generated by Django 3.0.5 on 2020-04-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=64)),
                ('currSymKey', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('email', models.CharField(default='', max_length=64)),
                ('isAdmin', models.BooleanField(default=False)),
                ('symKey', models.BinaryField()),
                ('publicKey', models.CharField(max_length=2000)),
                ('privateKey', models.CharField(max_length=2000)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groupchat.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='group', to='groupchat.Message'),
        ),
    ]
