# Generated by Django 3.0.5 on 2020-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_auto_20200411_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.BinaryField(),
        ),
    ]
