# Generated by Django 3.0.5 on 2020-04-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0006_auto_20200411_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='publicKey',
            field=models.BinaryField(),
        ),
    ]
