# Generated by Django 3.0.5 on 2020-04-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0008_auto_20200411_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=64),
        ),
    ]
