# Generated by Django 3.0.5 on 2020-04-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0010_auto_20200412_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='publicKey',
            field=models.CharField(max_length=2000),
        ),
    ]
