# Generated by Django 3.0.5 on 2020-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0011_auto_20200413_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.BinaryField(),
        ),
    ]
